// <auto-generated />
namespace Coticula2Face.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddVerdictAndProblem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddVerdictAndProblem));
        
        string IMigrationMetadata.Id
        {
            get { return "201503091615078_AddVerdictAndProblem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
